const ENV = {
    API_URL: 'https://cinema.webcloudlab.ru/api',
    API_URL_UPLOADS_ACTORS: '/api/uploads/actors/',
    API_URL_UPLOADS_MOVIES: '/api/uploads/movies/',
    API_URL_UPLOADS_MAIN_SLIDER: '/api/uploads/slider/main/',
    API_ACTORS: '/actors',
    API_MOVIE_ACTORS: '/movie_actors',
    API_ADD_ACTOR: '/add-actor',
    API_MOVIES_COUNT: '/movies-count',
    API_MOVIE: '/movie/',
    API_MOVIE_PROPERTIES: '/properties/',
    API_MOVIES: '/movies',
    API_LAST_MOVIES: '/last-movies',
    API_TOP_MOVIES: '/top-movies',
    API_ADD_MOVIE: '/add-movie',
    API_SEARCH_MOVIE: '/search-movie',
    API_SET_MOVIE_RATING: '/set-rating',
    API_GET_MOVIE_RATING: '/get-rating/',
    API_MOVIE_FAVORITE: '/add-favorite',
    API_MOVIES_FAVORITES: '/favorites',

    API_USERS: '/users',
    API_CREATE_USER: '/create-user/',
    API_AUTH: '/auth/',
    API_LOGOUT: '/logout/',
    API_REFRESH_TOKEN: '/refresh-token/',
    API_PROFILE: '/profile/',

    API_SLIDES: '/get-slides',
    API_ADD_SLIDE: '/add-slide',
    API_GET_SLIDE: '/get-slide',
    API_DELETE_SLIDE: '/delete-slide',
    API_UPDATE_SLIDE: '/update-slide',
    
    CLIENT_URL: 'https://cinema.webcloudlab.ru',
    MOVIES_URL: 'https://cinema.webcloudlab.ru/movies/',
    MOVIES: '/movies/',
    EDIT_SLIDER: '/admin/edit-slider/',
    ADD_MOVIE: '/admin/add-movie/',
    ADD_ACTOR: '/admin/add-actor/',
    ADMIN:'/admin/',
    //hhhh
}
export default ENV;